### ISSUE TITLE
Update of Beta - TPMS Testing

### ISSUE THREAD

**Issue by donok1** [fesch/CanZE4iOS#4]
Hi @fesch,

How is your work on the iOS version going ?
I saw in [https://github.com/fesch/CanZE/issues/689](https://github.com/fesch/CanZE/issues/689) that you couldn't test due to the lack of TPMS car.

I have an R110 -2019 and would be happy to help you test it !

Cheers

**Comment by fesch** [comment]
Hi @donok1 

Not being in charge of the iOS version, I can only pass the questions to @ik2wxx who, as far as I know, started the development of the new version.

**Comment by ik2wxx** [comment]
Hello, the TPMS section in the iOS app has never been tested, as any of the developer has both iPhone and a not Ph2 Zoe.
We can't develop this section without having the car for test, I'm sorry.
Roberto
