### ISSUE TITLE
wont work on ipad2 ?

### ISSUE THREAD

**Issue by AndyIreland** [fesch/CanZE4iOS#5]
i dont suppose I could get this to work on an old ipad2 I have just bought cheaply? - its on iOS 9.3.6

**Comment by ik2wxx** [comment]
I'm sorry, minimum iOS level is 12.3

**Comment by AndyIreland** [comment]
> I'm sorry, minimum iOS level is 12.3

ah right shame , thanks very much for answering

**Comment by AndyIreland** [comment]
> I'm sorry, minimum iOS level is 12.3

hi @ik2wxx - have got it working on my i[pad 2 with version 9.3.6 .
only problem I am facing is getting CANZE to recognise  the wifi dongle  by pressing the icon top right of screen or sliding out from the right of the screen. 
The ipad is detecting my wi-fi OBD2 dongle and it connects. 

I think I have got the right IP address of the dongle - the only thing I am stuck on is what port to write in - I tried 8080 but thats still not getting it connected

**Comment by ik2wxx** [comment]
It's tcp ip port 35000 on my dongle, maybe this info can help?

**Comment by AndyIreland** [comment]
> It's tcp ip port 35000 on my dongle, maybe this info can help?

thanks, i will try that figure and see if it works on mine

**Comment by AndyIreland** [comment]
@ik2wxx  - that worked a treat thank you
